apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrole-role
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - pods
      - services
    verbs:
      - get
      - list
      - watch
