apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-tmp
spec:
  volumeName: postgres-pv-tmp
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
